DELETE FROM OVERDRAFTS
WHERE (SELECT passport_number FROM BANK_CLIENTS WHERE id = 
            (SELECT client_id FROM BANK_ACCOUNTS WHERE overdraft_id = OVERDRAFTS.id)
        ) = "MT3451213";
DELETE FROM BANK_ACCOUNTS
WHERE client_id = (SELECT id FROM BANK_CLIENTS WHERE passport_number = "MT3451213");
DELETE FROM BANK_CLIENTS
WHERE passport_number = "MT3451213";