SELECT BANK_ACCOUNTS.id, ACCOUNT_TYPE.type, BANK_ACCOUNTS.balance, BANK_ACCOUNTS.total_transactions,
    BANK_ACCOUNTS.account_number, OVERDRAFTS.id, OVERDRAFTS.credit_sum, BANK_CLIENTS.id, BANK_ACCOUNTS.is_locked
FROM BANK_CLIENTS
JOIN BANK_ACCOUNTS
ON BANK_ACCOUNTS.client_id = BANK_CLIENTS.id
JOIN ACCOUNT_TYPE
ON BANK_ACCOUNTS.type_id = ACCOUNT_TYPE.id
LEFT JOIN OVERDRAFTS
ON BANK_ACCOUNTS.overdraft_id = OVERDRAFTS.id
WHERE BANK_ACCOUNTS.account_number = 64250856 AND BANK_CLIENTS.passport_number = "MP6549834";